version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    volumes:
      - ./mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-ui
    ports:
      - "27021:8081"
    environment:
      # Credentials Mongo Express uses to connect to MongoDB instance
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1234
      ME_CONFIG_MONGODB_SERVER: mongo
      # Mongo Express web UI credentials (for browser login screen)
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo-data: